"""Build an After Effects project (.aep) from a video and an .ass file by driving AfterFX.exe.

The driver script runs inside AE: new project -> import the video -> comp with the
video's size, frame rate and length -> run the lyrics JSX into it -> save. It reports
back through a small JSON status file; if AE may not write files (Preferences >
Scripting & Expressions), it shows the summary in AE instead and the caller only
sees the saved project.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path

from .fonts import FontIndex
from .jsxgen import Options, build_data, render
from .parser import load, parse_subs

DRIVER_PLACEHOLDER = "/*@@CONFIG@@*/null"

DRIVER = r"""//@target aftereffects
// Generated by ass2ae: builds a project from a video and the lyrics JSX. ES3.
(function () {
    var CFG = /*@@CONFIG@@*/null;
    var report = { ok: false, stage: "start", warnings: [] };

    function q(s) {
        s = String(s);
        var out = "\"";
        for (var i = 0; i < s.length; i++) {
            var c = s.charAt(i), code = s.charCodeAt(i);
            if (c === "\"" || c === "\\") { out += "\\" + c; }
            else if (code < 0x20 || code > 0x7e) {
                var h = code.toString(16);
                while (h.length < 4) { h = "0" + h; }
                out += "\\u" + h;
            } else { out += c; }
        }
        return out + "\"";
    }
    function toJson(v) {
        if (v === null || v === undefined) { return "null"; }
        if (typeof v === "number") { return isFinite(v) ? String(v) : "null"; }
        if (typeof v === "boolean") { return v ? "true" : "false"; }
        if (typeof v === "string") { return q(v); }
        var parts = [], k;
        if (v instanceof Array) {
            for (k = 0; k < v.length; k++) { parts.push(toJson(v[k])); }
            return "[" + parts.join(",") + "]";
        }
        for (k in v) {
            if (v.hasOwnProperty(k)) { parts.push(q(k) + ":" + toJson(v[k])); }
        }
        return "{" + parts.join(",") + "}";
    }
    function writeStatus() {
        try {
            var f = new File(CFG.status);
            f.encoding = "UTF-8";
            if (!f.open("w")) { return false; }
            f.write(toJson(report));
            f.close();
            return true;
        } catch (e) {
            return false;
        }
    }

    try {
        report.stage = "new project";
        if (!app.newProject()) { throw new Error("A new project was not created (the save prompt was cancelled)."); }
        report.stage = "import video";
        var footage = app.project.importFile(new ImportOptions(new File(CFG.video)));
        if (!(footage instanceof FootageItem) || !footage.hasVideo) {
            throw new Error("The video file has no video stream: " + CFG.video);
        }
        var fps = footage.frameRate > 0 ? footage.frameRate : CFG.fallbackFps;
        var duration = Math.max(footage.duration, CFG.lyricsEnd);
        var comp = app.project.items.addComp(CFG.compName, footage.width, footage.height,
                                             footage.pixelAspect, duration, fps);
        comp.layers.add(footage);
        report.stage = "lyrics";
        $.global.ASS2AE_HEADLESS = true;
        $.global.ASS2AE_TARGET = comp;
        try {
            $.evalFile(new File(CFG.lyrics));
        } finally {
            $.global.ASS2AE_HEADLESS = false;
            $.global.ASS2AE_TARGET = null;
        }
        var r = $.global.ASS2AE_RESULT;
        if (r) {
            report.summary = r.summary;
            report.warnings = r.warnings;
        }
        report.video = { width: footage.width, height: footage.height, fps: fps, duration: footage.duration };
        report.stage = "save";
        app.project.save(new File(CFG.aep));
        report.ok = true;
        report.stage = "done";
    } catch (e) {
        report.error = e.toString();
    }
    if (!writeStatus()) {
        var msg = report.ok ? "ass2ae: saved " + CFG.aep : "ass2ae failed at " + report.stage + ": " + report.error;
        if (report.summary) {
            msg += "\nLayers: " + report.summary.layers + "   Furigana: " + report.summary.furigana +
                   "   Markers: " + report.summary.markers;
        }
        msg += "\nWarnings: " + report.warnings.length;
        for (var w = 0; w < report.warnings.length && w < 10; w++) { msg += "\n- " + report.warnings[w]; }
        alert(msg);
    }
})();
"""


# ------------------------------------------------------------- After Effects

_AE_DIR = re.compile(r"Adobe After Effects (?:CC )?(\d{4})", re.I)


def ae_year(path: str | Path) -> int | None:
    m = _AE_DIR.search(str(path))
    return int(m.group(1)) if m else None


def find_afterfx() -> list[Path]:
    """Installed AfterFX.exe files, newest version first."""
    roots = {os.environ.get("ProgramFiles", r"C:\Program Files"), r"C:\Program Files"}
    found: list[Path] = []
    for root in roots:
        adobe = Path(root) / "Adobe"
        if not adobe.is_dir():
            continue
        for d in adobe.glob("Adobe After Effects*"):
            exe = d / "Support Files" / "AfterFX.exe"
            if exe.is_file() and exe not in found:
                found.append(exe)
    return sorted(found, key=lambda p: (ae_year(p) or 0, str(p)), reverse=True)


def afterfx_running() -> bool:
    try:
        out = subprocess.run(["tasklist", "/FI", "IMAGENAME eq AfterFX.exe", "/NH"], capture_output=True,
                             text=True, creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0)).stdout
    except OSError:
        return False
    return "AfterFX.exe" in out


# ------------------------------------------------------------------ building

@dataclass
class Job:
    ass: Path
    video: Path
    aep: Path
    work: Path
    lyrics: Path
    driver: Path
    status: Path
    data: dict
    started: float = 0.0


@dataclass
class BuildResult:
    ok: bool
    saved: bool
    summary: dict | None = None
    warnings: list[str] = field(default_factory=list)
    error: str | None = None
    stage: str | None = None
    video: dict | None = None
    status_written: bool = True


def work_dir() -> Path:
    base = Path(os.environ.get("LOCALAPPDATA") or Path.home()) / "ass2ae" / "runs"
    d = base / (time.strftime("%Y%m%d-%H%M%S") + "-" + uuid.uuid4().hex[:6])
    d.mkdir(parents=True, exist_ok=True)
    return d


def prepare(ass: str | Path, video: str | Path, aep: str | Path, opts: Options,
            styles: list[str] | None = None, fonts: FontIndex | None = None,
            encoding: str = "utf-8-sig") -> Job:
    """Convert the lyrics and write the driver script. Nothing runs in AE yet."""
    ass, video, aep = Path(ass).resolve(), Path(video).resolve(), Path(aep).resolve()
    subs = load(str(ass), encoding)
    result = parse_subs(subs, styles)
    if not opts.comp_name:
        opts.comp_name = video.stem
    data = build_data(subs, result, opts, ass.name, fonts)
    work = work_dir()
    lyrics = work / "lyrics.jsx"
    lyrics.write_text(render(data), encoding="ascii", newline="\n")
    status = work / "status.json"
    lyrics_end = max([l["outPoint"] for l in data["lines"]] or [0])
    config = {
        "video": str(video),
        "aep": str(aep),
        "lyrics": str(lyrics),
        "status": str(status),
        "compName": opts.comp_name,
        "fallbackFps": float(opts.fps),
        "lyricsEnd": lyrics_end,
    }
    driver = work / "build_project.jsx"
    driver.write_text(DRIVER.replace(DRIVER_PLACEHOLDER, json.dumps(config, ensure_ascii=True)),
                      encoding="ascii", newline="\n")
    return Job(ass, video, aep, work, lyrics, driver, status, data)


def launch(job: Job, afterfx: str | Path) -> None:
    """Hand the driver to AE (starting AE if needed). Returns immediately."""
    job.started = time.time()
    subprocess.Popen([str(afterfx), "-r", str(job.driver)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                     creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))


def poll(job: Job, grace: float = 5.0) -> BuildResult | None:
    """None while AE is still working."""
    if job.status.is_file():
        try:
            rep = json.loads(job.status.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return None  # being written
        saved = job.aep.is_file() and job.aep.stat().st_mtime >= job.started - 1
        return BuildResult(ok=bool(rep.get("ok")), saved=saved, summary=rep.get("summary"),
                           warnings=list(rep.get("warnings") or []), error=rep.get("error"),
                           stage=rep.get("stage"), video=rep.get("video"))
    if job.aep.is_file() and job.aep.stat().st_mtime >= job.started - 1:
        age = time.time() - job.aep.stat().st_mtime
        if age > grace:  # saved, but no status file: AE may not write files; it showed an alert instead
            return BuildResult(ok=True, saved=True, warnings=list(job.data["warnings"]), status_written=False)
    return None


def wait(job: Job, timeout: float = 3600, interval: float = 1.0, on_tick=None) -> BuildResult:
    while True:
        res = poll(job)
        if res is not None:
            return res
        elapsed = time.time() - job.started
        if on_tick:
            on_tick(elapsed)
        if elapsed > timeout:
            return BuildResult(ok=False, saved=False, error="timed out waiting for After Effects")
        time.sleep(interval)
