//@target aftereffects
// Generated by ass2ae. Re-run the converter instead of editing this file.
// ES3 only (ExtendScript): no let/const, arrow functions, template literals,
// forEach/map/indexOf on arrays, String#trim or JSON.
(function () {
    var DATA = {
 "tool": "ass2ae 0.1.0",
 "source": "en_spaces.ass",
 "mark": "[ass2ae]",
 "playRes": [
  1920,
  1080
 ],
 "comp": {
  "name": "en_spaces",
  "width": 1920,
  "height": 1080,
  "fps": 23.976023976023978,
  "fpsText": "24000/1001",
  "duration": 7.007
 },
 "options": {
  "styleMode": "template",
  "template": "KARA_TEMPLATE",
  "withAnimator": true,
  "newlineCounts": false,
  "fontScale": 0.7,
  "sungColor": null,
  "furiScale": 0.5
 },
 "amountExpression": "var acc = 0, amt = 0;\nfor (var k = 1; k <= marker.numKeys; k++) {\n  var m = marker.key(k), n = m.comment.length;\n  if (textIndex <= acc + n) {\n    var s = m.time + m.duration * (textIndex - acc - 1) / n;\n    amt = linear(time, s, s + m.duration / n, 0, 100);\n    break;\n  }\n  acc += n;\n}\namt;",
 "fontMetrics": {},
 "styles": {
  "EN": {
   "family": "Arial",
   "bold": false,
   "italic": false,
   "fauxBold": false,
   "fauxItalic": false,
   "fonts": [],
   "size": 64,
   "fill": [
    1.0,
    1.0,
    1.0
   ],
   "stroke": [
    0.0,
    0.0,
    0.0
   ],
   "sung": [
    1.0,
    1.0,
    0.0
   ],
   "outline": 3,
   "scaledBorder": true,
   "scaleX": 100,
   "scaleY": 100,
   "spacing": 0
  }
 },
 "lines": [
  {
   "n": 1,
   "event": 1,
   "style": "EN",
   "name": "KARA_0001_Hello wo",
   "comment": "[ass2ae] line=0001 event=1 style=EN",
   "text": "Hello world again",
   "inPoint": 1.001,
   "outPoint": 2.002,
   "start": 1,
   "end": 2,
   "inFrame": 24,
   "outFrame": 48,
   "alignment": 2,
   "justify": "center",
   "x": 960,
   "y": 1020,
   "positioned": false,
   "angle": 0,
   "markers": [
    {
     "t": 1,
     "d": 0.2,
     "c": "Hel",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "20",
      "furi": "[]",
      "event": "1",
      "fx": ""
     }
    },
    {
     "t": 1.2,
     "d": 0.15,
     "c": "lo ",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "15",
      "furi": "[]",
      "event": "1",
      "fx": ""
     }
    },
    {
     "t": 1.35,
     "d": 0.3,
     "c": "world ",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "30",
      "furi": "[]",
      "event": "1",
      "fx": ""
     }
    },
    {
     "t": 1.65,
     "d": 0.1,
     "c": "again",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "1",
      "fx": ""
     }
    }
   ],
   "furiStyle": null,
   "furi": []
  },
  {
   "n": 2,
   "event": 2,
   "style": "EN",
   "name": "KARA_0002_I want t",
   "comment": "[ass2ae] line=0002 event=2 style=EN",
   "text": "I want to fly!",
   "inPoint": 2.002,
   "outPoint": 3.003,
   "start": 2,
   "end": 3,
   "inFrame": 48,
   "outFrame": 72,
   "alignment": 2,
   "justify": "center",
   "x": 960,
   "y": 1020,
   "positioned": false,
   "angle": 0,
   "markers": [
    {
     "t": 2,
     "d": 0.25,
     "c": "I want",
     "p": {
      "kind": ",k",
      "tag": ",k",
      "cs": "0,25",
      "furi": "[]",
      "event": "2",
      "fx": ""
     }
    },
    {
     "t": 2.25,
     "d": 0.25,
     "c": " to fly!",
     "p": {
      "kind": "k,k,k",
      "tag": "k,k,k",
      "cs": "0,25,0",
      "furi": "[]",
      "event": "2",
      "fx": ""
     }
    }
   ],
   "furiStyle": null,
   "furi": []
  },
  {
   "n": 3,
   "event": 3,
   "style": "EN",
   "name": "KARA_0003_one two ",
   "comment": "[ass2ae] line=0003 event=3 style=EN",
   "text": "one two three",
   "inPoint": 3.003,
   "outPoint": 3.5035,
   "start": 3,
   "end": 3.5,
   "inFrame": 72,
   "outFrame": 84,
   "alignment": 2,
   "justify": "center",
   "x": 960,
   "y": 1020,
   "positioned": false,
   "angle": 0,
   "markers": [
    {
     "t": 3,
     "d": 0.3,
     "c": "one ",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "30",
      "furi": "[]",
      "event": "3",
      "fx": ""
     }
    },
    {
     "t": 3.3,
     "d": 0.2,
     "c": "two three",
     "p": {
      "kind": "k,k",
      "tag": "k,k",
      "cs": "30,30",
      "furi": "[]",
      "event": "3",
      "fx": ""
     }
    }
   ],
   "furiStyle": null,
   "furi": []
  },
  {
   "n": 4,
   "event": 4,
   "style": "EN",
   "name": "KARA_0004_soft bre",
   "comment": "[ass2ae] line=0004 event=4 style=EN",
   "text": "soft break",
   "inPoint": 4.004,
   "outPoint": 5.005,
   "start": 4,
   "end": 5,
   "inFrame": 96,
   "outFrame": 120,
   "alignment": 2,
   "justify": "center",
   "x": 960,
   "y": 1020,
   "positioned": false,
   "angle": 0,
   "markers": [
    {
     "t": 4,
     "d": 0.5,
     "c": "soft ",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "50",
      "furi": "[]",
      "event": "4",
      "fx": ""
     }
    },
    {
     "t": 4.5,
     "d": 0.5,
     "c": "break",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "50",
      "furi": "[]",
      "event": "4",
      "fx": ""
     }
    }
   ],
   "furiStyle": null,
   "furi": []
  },
  {
   "n": 5,
   "event": 5,
   "style": "EN",
   "name": "KARA_0005_comment ",
   "comment": "[ass2ae] line=0005 event=5 style=EN",
   "text": "comment here",
   "inPoint": 5.005,
   "outPoint": 6.006,
   "start": 5,
   "end": 6,
   "inFrame": 120,
   "outFrame": 144,
   "alignment": 2,
   "justify": "center",
   "x": 960,
   "y": 1020,
   "positioned": false,
   "angle": 0,
   "markers": [
    {
     "t": 5,
     "d": 0.4,
     "c": "comment",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "40",
      "furi": "[]",
      "event": "5",
      "fx": ""
     }
    },
    {
     "t": 5.4,
     "d": 0.4,
     "c": " here",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "40",
      "furi": "[]",
      "event": "5",
      "fx": ""
     }
    }
   ],
   "furiStyle": null,
   "furi": []
  }
 ],
 "warnings": [
  "event #3: karaoke runs 0.400s past the line end (0:00:03.500); 2 syllable(s) truncated"
 ]
};

    var MARK = DATA.mark;
    var MN = {
        textProps: "ADBE Text Properties",
        textDoc: "ADBE Text Document",
        animators: "ADBE Text Animators",
        animator: "ADBE Text Animator",
        animProps: "ADBE Text Animator Properties",
        fill: "ADBE Text Fill Color",
        selectors: "ADBE Text Selectors",
        exprSel: "ADBE Text Expressible Selector",
        exprAmount: "ADBE Text Expressible Amount",
        basedOn: "ADBE Text Range Type2",
        marker: "ADBE Marker",
        transform: "ADBE Transform Group",
        anchor: "ADBE Anchor Point",
        position: "ADBE Position",
        rotation: "ADBE Rotate Z"
    };
    var BASED_ON_CHARACTERS = 1;

    var warnings = [];
    var warnedKeys = {};
    function warn(msg) { warnings.push(msg); }
    function warnOnce(key, msg) {
        if (!warnedKeys[key]) {
            warnedKeys[key] = true;
            warn(msg);
        }
    }

    function startsWith(s, prefix) {
        return typeof s === "string" && s.substr(0, prefix.length) === prefix;
    }
    function lower(s) { return String(s).toLowerCase(); }
    function stripNewlines(s) { return String(s).replace(/[\r\n\u0003]/g, ""); }
    function unifyNewlines(s) { return String(s).replace(/\r\n|[\n\u0003]/g, "\r"); }

    // ---------------------------------------------------------------- fonts ---

    function u16(s, i) { return (s.charCodeAt(i) << 8) | s.charCodeAt(i + 1); }
    function s16(s, i) { var v = u16(s, i); return v >= 0x8000 ? v - 0x10000 : v; }
    function u32(s, i) { return u16(s, i) * 65536 + u16(s, i + 2); }
    function readAt(f, pos, len) { f.seek(pos, 0); return f.read(len); }

    function tableDir(f, offset) {
        var n = u16(readAt(f, offset, 12), 4);
        var dir = readAt(f, offset + 12, n * 16);
        var tables = {};
        for (var i = 0; i < n; i++) {
            tables[dir.substr(i * 16, 4)] = { off: u32(dir, i * 16 + 8), len: u32(dir, i * 16 + 12) };
        }
        return tables;
    }

    function postScriptName(f, tables) {
        var t = tables["name"];
        if (!t) { return ""; }
        var head = readAt(f, t.off, 6);
        var count = u16(head, 2);
        var strings = t.off + u16(head, 4);
        var recs = readAt(f, t.off + 6, count * 12);
        for (var i = 0; i < count; i++) {
            var r = i * 12;
            if (u16(recs, r + 6) !== 6) { continue; }
            var platform = u16(recs, r);
            var len = u16(recs, r + 8);
            var raw = readAt(f, strings + u16(recs, r + 10), len);
            if (platform === 1) { return raw; }
            var out = "";
            for (var j = 0; j + 1 < len; j += 2) { out += String.fromCharCode(u16(raw, j)); }
            return out;
        }
        return "";
    }

    // libass sizes fonts so that OS/2 usWinAscent+usWinDescent equals the ASS font
    // size (falling back to typo, then hhea metrics). Returns ratios per em.
    function readFontMetrics(path, psName) {
        var f = new File(path);
        if (!f.exists) { return null; }
        f.encoding = "BINARY";
        if (!f.open("r")) { return null; }
        try {
            var header = readAt(f, 0, 12);
            var offsets = [0];
            if (header.substr(0, 4) === "ttcf") {
                var n = u32(header, 8);
                var list = readAt(f, 12, n * 4);
                offsets = [];
                for (var i = 0; i < n; i++) { offsets.push(u32(list, i * 4)); }
            }
            for (var k = 0; k < offsets.length; k++) {
                var t = tableDir(f, offsets[k]);
                if (offsets.length > 1 && psName && postScriptName(f, t) !== psName) { continue; }
                if (!t["head"] || !t["hhea"]) { return null; }
                var upm = u16(readAt(f, t["head"].off + 18, 2), 0);
                var a = 0, d = 0;
                if (t["OS/2"]) {
                    var os2 = readAt(f, t["OS/2"].off + 68, 10);
                    a = s16(os2, 6);
                    d = s16(os2, 8);
                    if (a + d === 0) {
                        a = s16(os2, 0);
                        d = -s16(os2, 2);
                    }
                }
                if (a + d === 0) {
                    var hhea = readAt(f, t["hhea"].off + 4, 4);
                    a = s16(hhea, 0);
                    d = -s16(hhea, 2);
                }
                if (upm <= 0 || a + d <= 0) { return null; }
                return { em: upm / (a + d), asc: a / upm, desc: d / upm, source: "font file" };
            }
            return null;
        } catch (e) {
            return null;
        } finally {
            f.close();
        }
    }

    function hasFontsApi() {
        try { return app.fonts !== undefined && app.fonts !== null; } catch (e) { return false; }
    }

    function aeFontByPostScript(ps) {
        if (!hasFontsApi() || !ps) { return null; }
        var list = app.fonts.getFontsByPostScriptName(ps);
        for (var i = 0; list && i < list.length; i++) {
            if (!list[i].isSubstitute) { return list[i]; }
        }
        return null;
    }

    function styleRank(styleName, bold, italic) {
        var s = lower(styleName);
        var isBold = /bold|black|heavy|semibold|demibold/.test(s);
        var isItalic = /italic|oblique/.test(s);
        var rank = (isItalic === italic ? 0 : 2) + (isBold === bold ? 0 : 1);
        if (!bold && !italic && /^(regular|normal|book|roman|plain|w3|r)$/.test(s)) { rank -= 1; }
        return rank;
    }

    function aeFontByFamily(family, bold, italic) {
        if (!hasFontsApi()) { return null; }
        var key = lower(family);
        var best = null, bestRank = 99;
        var groups = app.fonts.allFonts;
        for (var g = 0; g < groups.length; g++) {
            var group = groups[g];
            for (var i = 0; i < group.length; i++) {
                var f = group[i];
                if (f.isSubstitute) { continue; }
                var names = [f.familyName, f.nativeFamilyName, f.fullName, f.nativeFullName];
                var hit = false;
                for (var j = 0; j < names.length; j++) {
                    if (names[j] && lower(names[j]) === key) { hit = true; }
                }
                if (!hit) { continue; }
                var rank = styleRank(f.styleName, bold, italic);
                if (rank < bestRank) {
                    best = f;
                    bestRank = rank;
                }
            }
        }
        return best;
    }

    function metricsFor(ps, aeFont) {
        if (DATA.fontMetrics[ps]) { return DATA.fontMetrics[ps]; }
        if (aeFont && aeFont.location) { return readFontMetrics(aeFont.location, ps); }
        return null;
    }

    var resolvedFonts = {};
    // Returns {ps, metrics} or null (null = keep AE's default font).
    function resolveFont(styleName, st) {
        if (resolvedFonts.hasOwnProperty(styleName)) { return resolvedFonts[styleName]; }
        var result = null, i, c, f;
        if (hasFontsApi()) {
            for (i = 0; !result && i < st.fonts.length; i++) {
                c = st.fonts[i];
                if (c.source !== "fontTools") { continue; }
                f = aeFontByPostScript(c.ps);
                if (f) { result = { ps: c.ps, metrics: metricsFor(c.ps, f) }; }
            }
            if (!result) {
                f = aeFontByFamily(st.family, st.bold, st.italic);
                if (f) { result = { ps: f.postScriptName, metrics: metricsFor(f.postScriptName, f) }; }
            }
            for (i = 0; !result && i < st.fonts.length; i++) {
                c = st.fonts[i];
                if (c.source !== "font-map") { continue; }
                f = aeFontByPostScript(c.ps);
                if (f) {
                    result = { ps: c.ps, metrics: metricsFor(c.ps, f) };
                    warn("Style " + styleName + ": font '" + st.family + "' not found by app.fonts; using --font-map entry " + c.ps);
                }
            }
        } else {
            for (i = 0; !result && i < st.fonts.length; i++) {
                c = st.fonts[i];
                result = { ps: c.ps, metrics: metricsFor(c.ps, null) };
            }
            warn("app.fonts is not available (After Effects 24.0+); font names could not be verified");
        }
        if (!result) {
            warn("Style " + styleName + ": font '" + st.family + "' not found; using the default font. Add it to --font-map.");
        } else if (!result.metrics) {
            warn("Style " + styleName + ": no metrics for " + result.ps + "; font size uses --font-scale and vertical alignment uses the text box");
        }
        resolvedFonts[styleName] = result;
        return result;
    }

    // ------------------------------------------------------------------ comp ---

    function fpsMatches(comp) {
        return Math.abs(comp.frameRate - DATA.comp.fps) < 0.0005;
    }

    function targetComp() {
        var item = app.project ? app.project.activeItem : null;
        // Set by driver scripts (project builder, tests): a CompItem to fill, or "new".
        var forced = $.global.ASS2AE_TARGET;
        if (forced === "new") {
            item = null;
        } else if (forced) {
            return forced;
        }
        if (item !== null && item instanceof CompItem) {
            if (!fpsMatches(item)) {
                warn("Active comp runs at " + item.frameRate + " fps, not " + DATA.comp.fpsText +
                     "; in/out points follow the comp's frames");
            }
            if (item.duration < DATA.comp.duration) {
                warn("Active comp is shorter (" + item.duration + "s) than the lyrics (" + DATA.comp.duration + "s)");
            }
            return item;
        }
        if (!app.project) { app.newProject(); }
        return app.project.items.addComp(DATA.comp.name, DATA.comp.width, DATA.comp.height, 1,
                                         DATA.comp.duration, DATA.comp.fps);
    }

    function removeGenerated(comp) {
        var removed = 0;
        for (var i = comp.numLayers; i >= 1; i--) {
            var layer = comp.layer(i);
            if (startsWith(layer.comment, MARK)) {
                layer.locked = false;
                layer.remove();
                removed++;
            }
        }
        return removed;
    }

    function findTemplate(comp, styleName) {
        return findNamed(comp, [DATA.options.template + "_" + styleName, DATA.options.template]);
    }

    function findFuriTemplate(comp, styleName) {
        return findNamed(comp, [DATA.options.template + "_FURI_" + styleName, DATA.options.template + "_FURI"]);
    }

    // First text layer (not generated by us) whose name is in names, in order of preference.
    function findNamed(comp, names) {
        for (var n = 0; n < names.length; n++) {
            for (var i = 1; i <= comp.numLayers; i++) {
                var layer = comp.layer(i);
                if (layer.name === names[n] && layer instanceof TextLayer && !startsWith(layer.comment, MARK)) {
                    return layer;
                }
            }
        }
        return null;
    }

    // ---------------------------------------------------------------- layers ---

    function textDocProp(layer) {
        return layer.property(MN.textProps).property(MN.textDoc);
    }

    var JUSTIFY = {
        left: ParagraphJustification.LEFT_JUSTIFY,
        center: ParagraphJustification.CENTER_JUSTIFY,
        right: ParagraphJustification.RIGHT_JUSTIFY
    };

    function trySet(obj, key, value, what) {
        try {
            obj[key] = value;
        } catch (e) {
            warnOnce("set " + key, "Could not set TextDocument." + key + " (" + what + "): " + e.toString());
        }
    }

    function vscaleOf(td) {
        try { return td.verticalScale || 1; } catch (e) { return 1; }
    }

    function styleTextDocument(td, justify, st, font, sy) {
        try { td.resetCharStyle(); } catch (e1) {}
        try { td.resetParagraphStyle(); } catch (e2) {}
        if (font) { td.font = font.ps; }
        var height = st.size * sy;  // ASS font size: ascent + descent, in comp pixels
        var em = height * (font && font.metrics ? font.metrics.em : DATA.options.fontScale);
        td.fontSize = em;
        td.applyFill = true;
        td.fillColor = st.fill;
        if (st.outline > 0) {
            td.applyStroke = true;
            td.strokeColor = st.stroke;
            td.strokeWidth = st.outline * 2 * (st.scaledBorder ? sy : 1);
            td.strokeOverFill = false;
        } else {
            td.applyStroke = false;
        }
        td.justification = JUSTIFY[justify];
        if (st.fauxBold) { trySet(td, "fauxBold", true, "bold"); }
        if (st.fauxItalic) { trySet(td, "fauxItalic", true, "italic"); }
        if (st.spacing !== 0) { trySet(td, "tracking", st.spacing * sy / em * 1000, "spacing"); }
        if (st.scaleX !== 100) { trySet(td, "horizontalScale", st.scaleX / 100, "ScaleX"); }
        if (st.scaleY !== 100) { trySet(td, "verticalScale", st.scaleY / 100, "ScaleY"); }
        // libass stacks lines by the font height (ascent + descent)
        trySet(td, "autoLeading", false, "line spacing");
        trySet(td, "leading", height * st.scaleY / 100, "line spacing");
    }

    function clearMarkers(layer) {
        var mk = layer.property(MN.marker);
        for (var k = mk.numKeys; k >= 1; k--) { mk.removeKey(k); }
    }

    // Copy of a template text layer with new text (scale shrinks font size and stroke).
    function templateCopy(tmpl, text, scale) {
        var layer = tmpl.duplicate();
        layer.locked = false;
        layer.enabled = true;
        layer.guideLayer = false;
        clearMarkers(layer);
        var tprop = textDocProp(layer);
        if (tprop.numKeys > 0) {
            warnOnce("tmplkeys " + tmpl.name, "Template " + tmpl.name + " has Source Text keyframes; they were removed on the copies");
            for (var k = tprop.numKeys; k >= 1; k--) { tprop.removeKey(k); }
        }
        var tdoc = tprop.value;
        tdoc.text = text;
        if (scale !== 1) {
            tdoc.fontSize = tdoc.fontSize * scale;
            if (tdoc.applyStroke) { tdoc.strokeWidth = tdoc.strokeWidth * scale; }
        }
        tprop.setValue(tdoc);
        var metrics = DATA.fontMetrics[tdoc.font] || readFontMetrics(tdoc.fontLocation, tdoc.font);
        if (!metrics) {
            warnOnce("tmplmetrics " + tdoc.font, "No metrics for template font " + tdoc.font +
                     "; vertical alignment uses the text box");
        }
        return { layer: layer, metrics: metrics };
    }

    // New text layer styled from an ASS style.
    function styledText(comp, text, styleKey, justify, sy) {
        var st = DATA.styles[styleKey];
        var layer = comp.layers.addText(text);
        var font = resolveFont(styleKey, st);
        var prop = textDocProp(layer);
        var td = prop.value;
        styleTextDocument(td, justify, st, font, sy);
        prop.setValue(td);
        return { layer: layer, metrics: font ? font.metrics : null };
    }

    function setTiming(comp, layer, line) {
        layer.startTime = 0;
        // libass shows a line on frames whose time t satisfies start <= t < end, so the in point
        // is the first frame at or after start. AE keeps its own frame grid (a 23.976 comp is
        // exactly 23.976 fps), so in/out are always whole frames of the target comp.
        var inF = line.inFrame, outF = line.outFrame;
        if (!fpsMatches(comp)) {
            inF = Math.ceil(line.start / comp.frameDuration - 1e-6);
            outF = Math.ceil(line.end / comp.frameDuration - 1e-6);
            if (outF <= inF) { outF = inF + 1; }
        }
        var inP = inF * comp.frameDuration, outP = outF * comp.frameDuration;
        // On text layers, setting inPoint keeps the layer's length (the out point moves
        // with it), so set the in point first and trim the out point afterwards.
        layer.inPoint = inP;
        layer.outPoint = outP;
    }

    function createLayer(comp, line, sy) {
        var res = null;
        if (DATA.options.styleMode === "template") {
            var tmpl = findTemplate(comp, line.style);
            if (tmpl) {
                res = templateCopy(tmpl, line.text, 1);
            } else {
                warnOnce("tmpl " + line.style, "No " + DATA.options.template + "_" + line.style + " or " +
                         DATA.options.template + " text layer in the comp; style " + line.style + " uses ASS styling");
            }
        }
        if (!res) { res = styledText(comp, line.text, line.style, line.justify, sy); }
        res.layer.name = line.name;
        res.layer.comment = line.comment;
        setTiming(comp, res.layer, line);
        return res;
    }

    // Template mode: <template>_FURI_<style>, <template>_FURI, else the line's template at
    // half size (karaskel's furigana scale). ASS mode: the "<style>-furigana" style.
    function createFuri(comp, line, group, sy) {
        var res = null;
        if (DATA.options.styleMode === "template") {
            var ft = findFuriTemplate(comp, line.style);
            if (ft) {
                res = templateCopy(ft, group.text, 1);
            } else {
                var mt = findTemplate(comp, line.style);
                if (mt) { res = templateCopy(mt, group.text, DATA.options.furiScale); }
            }
        }
        if (!res) { res = styledText(comp, group.text, line.furiStyle, "center", sy); }
        res.layer.name = group.name;
        res.layer.comment = group.comment;
        setTiming(comp, res.layer, line);
        return res;
    }

    // Anchor the text box at the ASS alignment point: horizontally from the
    // text's bounding box, vertically from the baselines plus font ascent/descent
    // (libass's line box) when metrics are known, otherwise from the bounding box.
    function placeLayer(layer, line, metrics, sx, sy) {
        var t = line.inPoint;
        var rect = layer.sourceRectAtTime(t, false);
        var td = textDocProp(layer).valueAtTime(t, false);
        var col = line.alignment % 3;
        var ax = col === 1 ? rect.left : (col === 0 ? rect.left + rect.width : rect.left + rect.width / 2);
        var ay;
        var base = baselines(td);
        if (metrics && base) {
            var vscale = vscaleOf(td);
            var asc = td.fontSize * metrics.asc * vscale;
            var desc = td.fontSize * metrics.desc * vscale;
            if (line.alignment <= 3) {
                ay = base.last + desc;
            } else if (line.alignment >= 7) {
                ay = base.first - asc;
            } else {
                ay = (base.first - asc + base.last + desc) / 2;
            }
        } else {
            ay = line.alignment <= 3 ? rect.top + rect.height : (line.alignment >= 7 ? rect.top : rect.top + rect.height / 2);
        }
        var tr = layer.property(MN.transform);
        setStatic(tr.property(MN.anchor), [ax, ay]);
        setStatic(tr.property(MN.position), [line.x * sx, line.y * sy]);
        if (line.angle) { setStatic(tr.property(MN.rotation), -line.angle); }
    }

    // Template copies may carry keyframes, where setValue would throw.
    function setStatic(prop, value) {
        if (prop.numKeys > 0) {
            warnOnce("keys " + prop.matchName, "Removed " + prop.name + " keyframes copied from the template");
            for (var k = prop.numKeys; k >= 1; k--) { prop.removeKey(k); }
        }
        prop.setValue(value);
    }

    // First and last baseline y in layer space.
    function baselines(td) {
        var locs = null;
        try { locs = td.baselineLocs; } catch (e) { locs = null; }
        if (locs && locs.length >= 4) {
            return { first: locs[1], last: locs[locs.length - 1] };
        }
        return null;
    }

    // ------------------------------------------------------------- furigana ---

    var SENTINEL = "|";

    function rightEdge(layer) {
        var r = layer.sourceRectAtTime(0, false);
        return r.left + r.width;
    }

    // Left-justified layer with the main layer's text style, to measure advance widths:
    // advance(s) = right edge of s + "|" minus right edge of "|" alone.
    function makeRuler(comp, source) {
        var layer = comp.layers.addText(SENTINEL);
        var td = textDocProp(source).value;
        td.justification = ParagraphJustification.LEFT_JUSTIFY;
        td.text = SENTINEL;
        textDocProp(layer).setValue(td);
        return { layer: layer, base: rightEdge(layer) };
    }

    function advance(ruler, s) {
        if (!s) { return 0; }
        var prop = textDocProp(ruler.layer);
        var td = prop.value;
        td.text = s + SENTINEL;
        prop.setValue(td);
        return rightEdge(ruler.layer) - ruler.base;
    }

    // Parent the furigana to its line and centre it above the base syllable, its line box
    // bottom on the top of the main line box (baseline - ascent).
    function placeFuri(main, mainMetrics, furi, furiMetrics, group, line, ruler) {
        var t = line.inPoint;
        var mtd = textDocProp(main).valueAtTime(t, false);
        var text = String(mtd.text);
        var k = 0, lineStart = 0, i;
        for (i = 0; i < group.start; i++) {
            if (text.charAt(i) === "\r") {
                k++;
                lineStart = i + 1;
            }
        }
        var lineEnd = lineStart;
        while (lineEnd < text.length && text.charAt(lineEnd) !== "\r") { lineEnd++; }
        var a = advance(ruler, text.substring(lineStart, group.start));
        var b = advance(ruler, text.substring(lineStart, group.end));
        var locs = null;
        try { locs = mtd.baselineLocs; } catch (e) { locs = null; }
        var x0, baseY, firstBase = 0;
        if (locs && locs.length >= 4 * (k + 1)) {
            x0 = locs[4 * k];
            baseY = locs[4 * k + 1];
            firstBase = locs[1];
        } else {
            warnOnce("nolocs", "TextDocument.baselineLocs is unavailable; furigana positions are estimated");
            var w = advance(ruler, text.substring(lineStart, lineEnd));
            var j = mtd.justification;
            x0 = j === ParagraphJustification.CENTER_JUSTIFY ? -w / 2 : (j === ParagraphJustification.RIGHT_JUSTIFY ? -w : 0);
            baseY = k * mtd.leading;
        }
        var top;
        if (mainMetrics) {
            top = baseY - mtd.fontSize * mainMetrics.asc * vscaleOf(mtd);
        } else {
            top = main.sourceRectAtTime(t, false).top + (baseY - firstBase);
        }
        var ftd = textDocProp(furi).valueAtTime(t, false);
        var fr = furi.sourceRectAtTime(t, false);
        var fb = baselines(ftd);
        var ax = fr.left + fr.width / 2;
        var ay = (furiMetrics && fb) ? fb.last + ftd.fontSize * furiMetrics.desc * vscaleOf(ftd) : fr.top + fr.height;
        try {
            furi.setParentWithJump(main);  // keep the copy's own transform values
        } catch (e2) {
            furi.parent = main;
        }
        var tr = furi.property(MN.transform);
        setStatic(tr.property(MN.anchor), [ax, ay]);
        setStatic(tr.property(MN.position), [x0 + (a + b) / 2, top]);
    }

    function addMarkers(layer, markers) {
        var mk = layer.property(MN.marker);
        for (var i = 0; i < markers.length; i++) {
            var m = markers[i];
            var mv = new MarkerValue(m.c);
            mv.duration = m.d;
            try {
                mv.setParameters(m.p);
            } catch (e) {
                warnOnce("params", "MarkerValue.setParameters failed: " + e.toString());
            }
            mk.setValueAtTime(m.t, mv);
        }
    }

    function propByPath(layer, path) {
        var p = layer;
        for (var i = 0; i < path.length; i++) { p = p.property(path[i]); }
        return p;
    }

    // Property references go stale after addProperty, so every step re-resolves its path.
    function addAnimator(layer, color) {
        var animators = layer.property(MN.textProps).property(MN.animators);
        var anim = animators.addProperty(MN.animator);
        var index = anim.propertyIndex;
        anim.name = "ass2ae karaoke";
        var base = [MN.textProps, MN.animators, index];
        propByPath(layer, base.concat([MN.animProps])).addProperty(MN.fill);
        propByPath(layer, base.concat([MN.animProps, MN.fill])).setValue(color);
        var sels = propByPath(layer, base.concat([MN.selectors]));
        for (var i = sels.numProperties; i >= 1; i--) {
            if (sels.property(i).matchName !== MN.exprSel) { sels.property(i).remove(); }
        }
        propByPath(layer, base.concat([MN.selectors])).addProperty(MN.exprSel);
        var sel = propByPath(layer, base.concat([MN.selectors])).property(MN.exprSel);
        sel.property(MN.basedOn).setValue(BASED_ON_CHARACTERS);
        sel.property(MN.exprAmount).expression = DATA.amountExpression;
    }

    // ------------------------------------------------------------ self check ---

    function selfCheck(layer, line) {
        var mk = layer.property(MN.marker);
        if (mk.numKeys !== line.markers.length) {
            warn(line.name + ": expected " + line.markers.length + " markers, found " + mk.numKeys);
        }
        var joined = "", prev = -1e9;
        for (var k = 1; k <= mk.numKeys; k++) {
            joined += mk.keyValue(k).comment;
            var t = mk.keyTime(k);
            if (!(t > prev)) { warn(line.name + ": marker times are not strictly increasing at #" + k); }
            prev = t;
        }
        var text = textDocProp(layer).value.text;
        var expected = DATA.options.newlineCounts ? unifyNewlines(text) : stripNewlines(text);
        if (DATA.options.newlineCounts) { joined = unifyNewlines(joined); }
        if (joined !== expected) {
            warn(line.name + ": marker comments do not add up to the layer text");
        }
        return mk.numKeys;
    }

    // ------------------------------------------------------------------ main ---

    function run() {
        var comp = targetComp();
        var removed = removeGenerated(comp);
        var sx = comp.width / DATA.playRes[0];
        var sy = comp.height / DATA.playRes[1];
        var made = [];
        var last = null, furiCount = 0;
        for (var i = 0; i < DATA.lines.length; i++) {
            var line = DATA.lines[i];
            var res = createLayer(comp, line, sy);
            // keep the block in order (KARA_0001 on top) wherever the first layer landed:
            // the comp top for new text layers, just above the template for copies
            if (last) { res.layer.moveAfter(last); }
            last = res.layer;
            placeLayer(res.layer, line, res.metrics, sx, sy);
            if (line.markers.length) {
                addMarkers(res.layer, line.markers);
                if (DATA.options.withAnimator) {
                    addAnimator(res.layer, DATA.options.sungColor || DATA.styles[line.style].sung);
                }
            }
            made.push({ layer: res.layer, line: line });
            var groups = line.furi || [];
            if (groups.length) {
                var ruler = makeRuler(comp, res.layer);
                for (var g = 0; g < groups.length; g++) {
                    var fres = createFuri(comp, line, groups[g], sy);
                    fres.layer.moveBefore(res.layer);
                    placeFuri(res.layer, res.metrics, fres.layer, fres.metrics, groups[g], line, ruler);
                    if (groups[g].markers.length) {
                        addMarkers(fres.layer, groups[g].markers);
                        if (DATA.options.withAnimator) {
                            addAnimator(fres.layer, DATA.options.sungColor || DATA.styles[line.furiStyle].sung);
                        }
                    }
                    made.push({ layer: fres.layer, line: groups[g] });
                    furiCount++;
                }
                ruler.layer.remove();
            }
        }
        var markerCount = 0;
        for (var j = 0; j < made.length; j++) {
            if (made[j].line.markers.length) { markerCount += selfCheck(made[j].layer, made[j].line); }
        }
        try { comp.openInViewer(); } catch (e) {}
        return { comp: comp.name, compId: comp.id, layers: made.length - furiCount, furigana: furiCount,
                 markers: markerCount, removed: removed };
    }

    // Redirect the viewer to a tiny dummy comp so AE does not re-render
    // the target on every layer change (extremely slow with video).
    var _redirect = null;
    try {
        _redirect = app.project.items.addComp("_ass2ae_redirect_", 4, 4, 1, 1, 1);
        _redirect.openInViewer();
    } catch (e) {}

    var summary = null;
    app.beginUndoGroup("ass2ae: " + DATA.source);
    try {
        summary = run();
    } catch (err) {
        warn("Stopped by an error: " + err.toString() + (err.line ? " (jsx line " + err.line + ")" : ""));
    } finally {
        app.endUndoGroup();
    }
    if (_redirect) { try { _redirect.remove(); } catch (e) {} }

    var all = DATA.warnings.concat(warnings);
    if ($.global.ASS2AE_HEADLESS) {
        $.global.ASS2AE_RESULT = { summary: summary, warnings: all, aeWarnings: warnings };
        return;
    }
    var msg = "ass2ae: " + DATA.source + "\n";
    if (summary) {
        msg += "Comp: " + summary.comp + "\nLayers: " + summary.layers + "   Furigana: " + summary.furigana +
               "   Markers: " + summary.markers +
               "   Replaced: " + summary.removed + "\n";
    }
    msg += "Warnings: " + all.length;
    var shown = Math.min(all.length, 15);
    for (var w = 0; w < shown; w++) { msg += "\n- " + all[w]; }
    if (all.length > shown) { msg += "\n(" + (all.length - shown) + " more; see the converter output)"; }
    alert(msg);
})();
