//@target aftereffects
// Generated by ass2ae. Re-run the converter instead of editing this file.
// ES3 only (ExtendScript): no let/const, arrow functions, template literals,
// forEach/map/indexOf on arrays, String#trim or JSON.
(function () {
    var DATA = {
 "tool": "ass2ae 0.1.0",
 "source": "templated.ass",
 "mark": "[ass2ae]",
 "playRes": [
  1920,
  1080
 ],
 "comp": {
  "name": "templated",
  "width": 1920,
  "height": 1080,
  "fps": 23.976023976023978,
  "fpsText": "24000/1001",
  "duration": 220.80391666666668
 },
 "options": {
  "styleMode": "template",
  "template": "KARA_TEMPLATE",
  "withAnimator": true,
  "newlineCounts": false,
  "fontScale": 0.7,
  "sungColor": null
 },
 "amountExpression": "var acc = 0, amt = 0;\nfor (var k = 1; k <= marker.numKeys; k++) {\n  var m = marker.key(k), n = m.comment.length;\n  if (textIndex <= acc + n) {\n    var s = m.time + m.duration * (textIndex - acc - 1) / n;\n    amt = linear(time, s, s + m.duration / n, 0, 100);\n    break;\n  }\n  acc += n;\n}\namt;",
 "fontMetrics": {},
 "styles": {
  "K2": {
   "family": "Gen Jyuu Gothic Bold",
   "bold": false,
   "italic": false,
   "fauxBold": false,
   "fauxItalic": false,
   "fonts": [],
   "size": 120,
   "fill": [
    1.0,
    1.0,
    1.0
   ],
   "stroke": [
    0.0,
    0.0,
    0.0
   ],
   "sung": [
    1.0,
    1.0,
    1.0
   ],
   "outline": 4,
   "scaledBorder": false,
   "scaleX": 100,
   "scaleY": 100,
   "spacing": 0
  },
  "K1": {
   "family": "Gen Jyuu Gothic Bold",
   "bold": false,
   "italic": false,
   "fauxBold": false,
   "fauxItalic": false,
   "fonts": [],
   "size": 120,
   "fill": [
    1.0,
    1.0,
    1.0
   ],
   "stroke": [
    0.0,
    0.0,
    0.0
   ],
   "sung": [
    1.0,
    1.0,
    1.0
   ],
   "outline": 4,
   "scaledBorder": false,
   "scaleX": 100,
   "scaleY": 100,
   "spacing": 0
  },
  "noK": {
   "family": "Noto Serif CJK JP Black",
   "bold": false,
   "italic": false,
   "fauxBold": false,
   "fauxItalic": false,
   "fonts": [],
   "size": 120,
   "fill": [
    1.0,
    1.0,
    1.0
   ],
   "stroke": [
    0.0,
    0.0,
    0.0
   ],
   "sung": [
    1.0,
    1.0,
    0.223529
   ],
   "outline": 4,
   "scaledBorder": false,
   "scaleX": 100,
   "scaleY": 100,
   "spacing": 0
  }
 },
 "lines": [
  {
   "n": 1,
   "event": 5,
   "style": "K2",
   "name": "KARA_0001_\u982d \u3067\u308f\u304b\u3063\u3066\u306f",
   "comment": "[ass2ae] line=0001 event=5 style=K2",
   "text": "\u982d \u3067\u308f\u304b\u3063\u3066\u306f\u5606\u3044\u305f",
   "inPoint": 26.109416666666668,
   "outPoint": 27.694333333333333,
   "inFrame": 626,
   "outFrame": 664,
   "alignment": 3,
   "justify": "right",
   "x": 1800,
   "y": 1040,
   "positioned": false,
   "angle": 0,
   "markers": [
    {
     "t": 26.07,
     "d": 0.33,
     "c": "\u982d",
     "p": {
      "kind": "k,k,k",
      "tag": "k,k,k",
      "cs": "8,12,13",
      "furi": "[[\"\u3042\",26.07,0.08,\"<\"],[\"\u305f\",26.15,0.12,\"<\"],[\"\u307e\",26.27,0.13,\"<\"]]",
      "event": "5",
      "fx": "A"
     }
    },
    {
     "t": 26.4,
     "d": 0.02,
     "c": " ",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "2",
      "furi": "[]",
      "event": "5",
      "fx": "A"
     }
    },
    {
     "t": 26.42,
     "d": 0.12,
     "c": "\u3067",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "12",
      "furi": "[]",
      "event": "5",
      "fx": "A"
     }
    },
    {
     "t": 26.54,
     "d": 0.1,
     "c": "\u308f",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "5",
      "fx": "A"
     }
    },
    {
     "t": 26.64,
     "d": 0.11,
     "c": "\u304b",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "11",
      "furi": "[]",
      "event": "5",
      "fx": "A"
     }
    },
    {
     "t": 26.75,
     "d": 0.1,
     "c": "\u3063",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "5",
      "fx": "A"
     }
    },
    {
     "t": 26.85,
     "d": 0.1,
     "c": "\u3066",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "5",
      "fx": "A"
     }
    },
    {
     "t": 26.95,
     "d": 0.11,
     "c": "\u306f",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "11",
      "furi": "[]",
      "event": "5",
      "fx": "A"
     }
    },
    {
     "t": 27.06,
     "d": 0.19,
     "c": "\u5606",
     "p": {
      "kind": "k,k",
      "tag": "k,k",
      "cs": "10,9",
      "furi": "[[\"\u306a\",27.06,0.1,\"<\"],[\"\u3052\",27.16,0.09,\"<\"]]",
      "event": "5",
      "fx": "A"
     }
    },
    {
     "t": 27.25,
     "d": 0.13,
     "c": "\u3044",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "13",
      "furi": "[]",
      "event": "5",
      "fx": "A"
     }
    },
    {
     "t": 27.38,
     "d": 0.29,
     "c": "\u305f",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "30",
      "furi": "[]",
      "event": "5",
      "fx": "A"
     }
    }
   ]
  },
  {
   "n": 2,
   "event": 6,
   "style": "K1",
   "name": "KARA_0002_\u8ee2\u304c\u3063\u3066\u304f\u69d8\u5b50\u3092",
   "comment": "[ass2ae] line=0002 event=6 style=K1",
   "text": "\u8ee2\u304c\u3063\u3066\u304f\u69d8\u5b50\u3092\u55e4\u3063\u305f",
   "inPoint": 27.652625,
   "outPoint": 29.27925,
   "inFrame": 663,
   "outFrame": 702,
   "alignment": 1,
   "justify": "left",
   "x": 120,
   "y": 840,
   "positioned": false,
   "angle": 0,
   "markers": [
    {
     "t": 27.63,
     "d": 0.2,
     "c": "\u8ee2",
     "p": {
      "kind": "k,k",
      "tag": "k,k",
      "cs": "10,10",
      "furi": "[[\"\u3053\",27.63,0.1,\"<\"],[\"\u308d\",27.73,0.1,\"<\"]]",
      "event": "6",
      "fx": "A"
     }
    },
    {
     "t": 27.83,
     "d": 0.11,
     "c": "\u304c",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "11",
      "furi": "[]",
      "event": "6",
      "fx": "A"
     }
    },
    {
     "t": 27.94,
     "d": 0.1,
     "c": "\u3063",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "6",
      "fx": "A"
     }
    },
    {
     "t": 28.04,
     "d": 0.1,
     "c": "\u3066",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "6",
      "fx": "A"
     }
    },
    {
     "t": 28.14,
     "d": 0.1,
     "c": "\u304f",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "6",
      "fx": "A"
     }
    },
    {
     "t": 28.24,
     "d": 0.2,
     "c": "\u69d8",
     "p": {
      "kind": "k,k",
      "tag": "k,k",
      "cs": "10,10",
      "furi": "[[\"\u3088\",28.24,0.1,\"<\"],[\"\u3046\",28.34,0.1,\"<\"]]",
      "event": "6",
      "fx": "A"
     }
    },
    {
     "t": 28.44,
     "d": 0.1,
     "c": "\u5b50",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[[\"\u3059\",28.44,0.1,\"<\"]]",
      "event": "6",
      "fx": "A"
     }
    },
    {
     "t": 28.54,
     "d": 0.1,
     "c": "\u3092",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "6",
      "fx": "A"
     }
    },
    {
     "t": 28.64,
     "d": 0.16,
     "c": "\u55e4",
     "p": {
      "kind": "k,k",
      "tag": "k,k",
      "cs": "8,8",
      "furi": "[[\"\u308f\",28.64,0.08,\"<\"],[\"\u3089\",28.72,0.08,\"<\"]]",
      "event": "6",
      "fx": "A"
     }
    },
    {
     "t": 28.8,
     "d": 0.17,
     "c": "\u3063",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "17",
      "furi": "[]",
      "event": "6",
      "fx": "A"
     }
    },
    {
     "t": 28.97,
     "d": 0.3,
     "c": "\u305f",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "30",
      "furi": "[]",
      "event": "6",
      "fx": "A"
     }
    }
   ]
  },
  {
   "n": 3,
   "event": 7,
   "style": "K2",
   "name": "KARA_0003_\u5bc2\u3057\u3044\u3068\u304b\u611b\u3068\u304b",
   "comment": "[ass2ae] line=0003 event=7 style=K2",
   "text": "\u5bc2\u3057\u3044\u3068\u304b\u611b\u3068\u304b",
   "inPoint": 29.27925,
   "outPoint": 30.28025,
   "inFrame": 702,
   "outFrame": 726,
   "alignment": 3,
   "justify": "right",
   "x": 1800,
   "y": 1040,
   "positioned": false,
   "angle": 0,
   "markers": [
    {
     "t": 29.25,
     "d": 0.2,
     "c": "\u5bc2",
     "p": {
      "kind": "k,k",
      "tag": "k,k",
      "cs": "10,10",
      "furi": "[[\"\u3055\",29.25,0.1,\"<\"],[\"\u3073\",29.35,0.1,\"<\"]]",
      "event": "7",
      "fx": "A"
     }
    },
    {
     "t": 29.45,
     "d": 0.1,
     "c": "\u3057",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "7",
      "fx": "A"
     }
    },
    {
     "t": 29.55,
     "d": 0.1,
     "c": "\u3044",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "7",
      "fx": "A"
     }
    },
    {
     "t": 29.65,
     "d": 0.1,
     "c": "\u3068",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "7",
      "fx": "A"
     }
    },
    {
     "t": 29.75,
     "d": 0.1,
     "c": "\u304b",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "7",
      "fx": "A"
     }
    },
    {
     "t": 29.85,
     "d": 0.2,
     "c": "\u611b",
     "p": {
      "kind": "k,k",
      "tag": "k,k",
      "cs": "10,10",
      "furi": "[[\"\u3042\",29.85,0.1,\"<\"],[\"\u3044\",29.95,0.1,\"<\"]]",
      "event": "7",
      "fx": "A"
     }
    },
    {
     "t": 30.05,
     "d": 0.1,
     "c": "\u3068",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "7",
      "fx": "A"
     }
    },
    {
     "t": 30.15,
     "d": 0.1,
     "c": "\u304b",
     "p": {
      "kind": "k",
      "tag": "k",
      "cs": "10",
      "furi": "[]",
      "event": "7",
      "fx": "A"
     }
    }
   ]
  },
  {
   "n": 4,
   "event": 12,
   "style": "noK",
   "name": "KARA_0004_\u526a\u8f2f/\u5b57\u5e55\uff1a\u574d\u65b9",
   "comment": "[ass2ae] line=0004 event=12 style=noK",
   "text": "\u526a\u8f2f/\u5b57\u5e55\uff1a\u574d\u65b9",
   "inPoint": 216.92504166666666,
   "outPoint": 219.80291666666668,
   "inFrame": 5201,
   "outFrame": 5270,
   "alignment": 8,
   "justify": "center",
   "x": 960,
   "y": 300,
   "positioned": false,
   "angle": 0,
   "markers": []
  }
 ],
 "warnings": [
  "event #5: karaoke runs 0.010s past the line end (0:00:27.670); 1 syllable(s) truncated"
 ]
};

    var MARK = DATA.mark;
    var MN = {
        textProps: "ADBE Text Properties",
        textDoc: "ADBE Text Document",
        animators: "ADBE Text Animators",
        animator: "ADBE Text Animator",
        animProps: "ADBE Text Animator Properties",
        fill: "ADBE Text Fill Color",
        selectors: "ADBE Text Selectors",
        exprSel: "ADBE Text Expressible Selector",
        exprAmount: "ADBE Text Expressible Amount",
        basedOn: "ADBE Text Range Type2",
        marker: "ADBE Marker",
        transform: "ADBE Transform Group",
        anchor: "ADBE Anchor Point",
        position: "ADBE Position",
        rotation: "ADBE Rotate Z"
    };
    var BASED_ON_CHARACTERS = 1;

    var warnings = [];
    var warnedKeys = {};
    function warn(msg) { warnings.push(msg); }
    function warnOnce(key, msg) {
        if (!warnedKeys[key]) {
            warnedKeys[key] = true;
            warn(msg);
        }
    }

    function startsWith(s, prefix) {
        return typeof s === "string" && s.substr(0, prefix.length) === prefix;
    }
    function lower(s) { return String(s).toLowerCase(); }
    function stripNewlines(s) { return String(s).replace(/[\r\n\u0003]/g, ""); }
    function unifyNewlines(s) { return String(s).replace(/\r\n|[\n\u0003]/g, "\r"); }

    // ---------------------------------------------------------------- fonts ---

    function u16(s, i) { return (s.charCodeAt(i) << 8) | s.charCodeAt(i + 1); }
    function s16(s, i) { var v = u16(s, i); return v >= 0x8000 ? v - 0x10000 : v; }
    function u32(s, i) { return u16(s, i) * 65536 + u16(s, i + 2); }
    function readAt(f, pos, len) { f.seek(pos, 0); return f.read(len); }

    function tableDir(f, offset) {
        var n = u16(readAt(f, offset, 12), 4);
        var dir = readAt(f, offset + 12, n * 16);
        var tables = {};
        for (var i = 0; i < n; i++) {
            tables[dir.substr(i * 16, 4)] = { off: u32(dir, i * 16 + 8), len: u32(dir, i * 16 + 12) };
        }
        return tables;
    }

    function postScriptName(f, tables) {
        var t = tables["name"];
        if (!t) { return ""; }
        var head = readAt(f, t.off, 6);
        var count = u16(head, 2);
        var strings = t.off + u16(head, 4);
        var recs = readAt(f, t.off + 6, count * 12);
        for (var i = 0; i < count; i++) {
            var r = i * 12;
            if (u16(recs, r + 6) !== 6) { continue; }
            var platform = u16(recs, r);
            var len = u16(recs, r + 8);
            var raw = readAt(f, strings + u16(recs, r + 10), len);
            if (platform === 1) { return raw; }
            var out = "";
            for (var j = 0; j + 1 < len; j += 2) { out += String.fromCharCode(u16(raw, j)); }
            return out;
        }
        return "";
    }

    // libass sizes fonts so that OS/2 usWinAscent+usWinDescent equals the ASS font
    // size (falling back to typo, then hhea metrics). Returns ratios per em.
    function readFontMetrics(path, psName) {
        var f = new File(path);
        if (!f.exists) { return null; }
        f.encoding = "BINARY";
        if (!f.open("r")) { return null; }
        try {
            var header = readAt(f, 0, 12);
            var offsets = [0];
            if (header.substr(0, 4) === "ttcf") {
                var n = u32(header, 8);
                var list = readAt(f, 12, n * 4);
                offsets = [];
                for (var i = 0; i < n; i++) { offsets.push(u32(list, i * 4)); }
            }
            for (var k = 0; k < offsets.length; k++) {
                var t = tableDir(f, offsets[k]);
                if (offsets.length > 1 && psName && postScriptName(f, t) !== psName) { continue; }
                if (!t["head"] || !t["hhea"]) { return null; }
                var upm = u16(readAt(f, t["head"].off + 18, 2), 0);
                var a = 0, d = 0;
                if (t["OS/2"]) {
                    var os2 = readAt(f, t["OS/2"].off + 68, 10);
                    a = s16(os2, 6);
                    d = s16(os2, 8);
                    if (a + d === 0) {
                        a = s16(os2, 0);
                        d = -s16(os2, 2);
                    }
                }
                if (a + d === 0) {
                    var hhea = readAt(f, t["hhea"].off + 4, 4);
                    a = s16(hhea, 0);
                    d = -s16(hhea, 2);
                }
                if (upm <= 0 || a + d <= 0) { return null; }
                return { em: upm / (a + d), asc: a / upm, desc: d / upm, source: "font file" };
            }
            return null;
        } catch (e) {
            return null;
        } finally {
            f.close();
        }
    }

    function hasFontsApi() {
        try { return app.fonts !== undefined && app.fonts !== null; } catch (e) { return false; }
    }

    function aeFontByPostScript(ps) {
        if (!hasFontsApi() || !ps) { return null; }
        var list = app.fonts.getFontsByPostScriptName(ps);
        for (var i = 0; list && i < list.length; i++) {
            if (!list[i].isSubstitute) { return list[i]; }
        }
        return null;
    }

    function styleRank(styleName, bold, italic) {
        var s = lower(styleName);
        var isBold = /bold|black|heavy|semibold|demibold/.test(s);
        var isItalic = /italic|oblique/.test(s);
        var rank = (isItalic === italic ? 0 : 2) + (isBold === bold ? 0 : 1);
        if (!bold && !italic && /^(regular|normal|book|roman|plain|w3|r)$/.test(s)) { rank -= 1; }
        return rank;
    }

    function aeFontByFamily(family, bold, italic) {
        if (!hasFontsApi()) { return null; }
        var key = lower(family);
        var best = null, bestRank = 99;
        var groups = app.fonts.allFonts;
        for (var g = 0; g < groups.length; g++) {
            var group = groups[g];
            for (var i = 0; i < group.length; i++) {
                var f = group[i];
                if (f.isSubstitute) { continue; }
                var names = [f.familyName, f.nativeFamilyName, f.fullName, f.nativeFullName];
                var hit = false;
                for (var j = 0; j < names.length; j++) {
                    if (names[j] && lower(names[j]) === key) { hit = true; }
                }
                if (!hit) { continue; }
                var rank = styleRank(f.styleName, bold, italic);
                if (rank < bestRank) {
                    best = f;
                    bestRank = rank;
                }
            }
        }
        return best;
    }

    function metricsFor(ps, aeFont) {
        if (DATA.fontMetrics[ps]) { return DATA.fontMetrics[ps]; }
        if (aeFont && aeFont.location) { return readFontMetrics(aeFont.location, ps); }
        return null;
    }

    var resolvedFonts = {};
    // Returns {ps, metrics} or null (null = keep AE's default font).
    function resolveFont(styleName, st) {
        if (resolvedFonts.hasOwnProperty(styleName)) { return resolvedFonts[styleName]; }
        var result = null, i, c, f;
        if (hasFontsApi()) {
            for (i = 0; !result && i < st.fonts.length; i++) {
                c = st.fonts[i];
                if (c.source !== "fontTools") { continue; }
                f = aeFontByPostScript(c.ps);
                if (f) { result = { ps: c.ps, metrics: metricsFor(c.ps, f) }; }
            }
            if (!result) {
                f = aeFontByFamily(st.family, st.bold, st.italic);
                if (f) { result = { ps: f.postScriptName, metrics: metricsFor(f.postScriptName, f) }; }
            }
            for (i = 0; !result && i < st.fonts.length; i++) {
                c = st.fonts[i];
                if (c.source !== "font-map") { continue; }
                f = aeFontByPostScript(c.ps);
                if (f) {
                    result = { ps: c.ps, metrics: metricsFor(c.ps, f) };
                    warn("Style " + styleName + ": font '" + st.family + "' not found by app.fonts; using --font-map entry " + c.ps);
                }
            }
        } else {
            for (i = 0; !result && i < st.fonts.length; i++) {
                c = st.fonts[i];
                result = { ps: c.ps, metrics: metricsFor(c.ps, null) };
            }
            warn("app.fonts is not available (After Effects 24.0+); font names could not be verified");
        }
        if (!result) {
            warn("Style " + styleName + ": font '" + st.family + "' not found; using the default font. Add it to --font-map.");
        } else if (!result.metrics) {
            warn("Style " + styleName + ": no metrics for " + result.ps + "; font size uses --font-scale and vertical alignment uses the text box");
        }
        resolvedFonts[styleName] = result;
        return result;
    }

    // ------------------------------------------------------------------ comp ---

    function fpsMatches(comp) {
        return Math.abs(comp.frameRate - DATA.comp.fps) < 0.0005;
    }

    function targetComp() {
        var item = app.project ? app.project.activeItem : null;
        var forced = $.global.ASS2AE_TARGET;  // test hook: a CompItem, or "new"
        if (forced === "new") {
            item = null;
        } else if (forced) {
            item = forced;
        }
        if (item !== null && item instanceof CompItem) {
            if (!fpsMatches(item)) {
                warn("Active comp runs at " + item.frameRate + " fps but in/out points were computed for " +
                     DATA.comp.fpsText + " fps");
            }
            if (item.duration < DATA.comp.duration) {
                warn("Active comp is shorter (" + item.duration + "s) than the lyrics (" + DATA.comp.duration + "s)");
            }
            return item;
        }
        if (!app.project) { app.newProject(); }
        var comp = app.project.items.addComp(DATA.comp.name, DATA.comp.width, DATA.comp.height, 1,
                                             DATA.comp.duration, DATA.comp.fps);
        comp.openInViewer();
        return comp;
    }

    function removeGenerated(comp) {
        var removed = 0;
        for (var i = comp.numLayers; i >= 1; i--) {
            var layer = comp.layer(i);
            if (startsWith(layer.comment, MARK)) {
                layer.locked = false;
                layer.remove();
                removed++;
            }
        }
        return removed;
    }

    function findTemplate(comp, styleName) {
        var names = [DATA.options.template + "_" + styleName, DATA.options.template];
        for (var n = 0; n < names.length; n++) {
            for (var i = 1; i <= comp.numLayers; i++) {
                var layer = comp.layer(i);
                if (layer.name === names[n] && layer instanceof TextLayer && !startsWith(layer.comment, MARK)) {
                    return layer;
                }
            }
        }
        return null;
    }

    // ---------------------------------------------------------------- layers ---

    function textDocProp(layer) {
        return layer.property(MN.textProps).property(MN.textDoc);
    }

    var JUSTIFY = {
        left: ParagraphJustification.LEFT_JUSTIFY,
        center: ParagraphJustification.CENTER_JUSTIFY,
        right: ParagraphJustification.RIGHT_JUSTIFY
    };

    function trySet(obj, key, value, what) {
        try {
            obj[key] = value;
        } catch (e) {
            warnOnce("set " + key, "Could not set TextDocument." + key + " (" + what + "): " + e.toString());
        }
    }

    function styleTextDocument(td, line, st, font, sy) {
        try { td.resetCharStyle(); } catch (e1) {}
        try { td.resetParagraphStyle(); } catch (e2) {}
        if (font) { td.font = font.ps; }
        var height = st.size * sy;  // ASS font size: ascent + descent, in comp pixels
        var em = height * (font && font.metrics ? font.metrics.em : DATA.options.fontScale);
        td.fontSize = em;
        td.applyFill = true;
        td.fillColor = st.fill;
        if (st.outline > 0) {
            td.applyStroke = true;
            td.strokeColor = st.stroke;
            td.strokeWidth = st.outline * 2 * (st.scaledBorder ? sy : 1);
            td.strokeOverFill = false;
        } else {
            td.applyStroke = false;
        }
        td.justification = JUSTIFY[line.justify];
        if (st.fauxBold) { trySet(td, "fauxBold", true, "bold"); }
        if (st.fauxItalic) { trySet(td, "fauxItalic", true, "italic"); }
        if (st.spacing !== 0) { trySet(td, "tracking", st.spacing * sy / em * 1000, "spacing"); }
        if (st.scaleX !== 100) { trySet(td, "horizontalScale", st.scaleX / 100, "ScaleX"); }
        if (st.scaleY !== 100) { trySet(td, "verticalScale", st.scaleY / 100, "ScaleY"); }
        // libass stacks lines by the font height (ascent + descent)
        trySet(td, "autoLeading", false, "line spacing");
        trySet(td, "leading", height * st.scaleY / 100, "line spacing");
    }

    function clearMarkers(layer) {
        var mk = layer.property(MN.marker);
        for (var k = mk.numKeys; k >= 1; k--) { mk.removeKey(k); }
    }

    function createLayer(comp, line, sy) {
        var st = DATA.styles[line.style];
        var layer = null, font = null, metrics = null;
        if (DATA.options.styleMode === "template") {
            var tmpl = findTemplate(comp, line.style);
            if (tmpl) {
                layer = tmpl.duplicate();
                layer.locked = false;
                layer.enabled = true;
                layer.guideLayer = false;
                clearMarkers(layer);
                var tprop = textDocProp(layer);
                if (tprop.numKeys > 0) {
                    warnOnce("tmplkeys", "Template " + tmpl.name + " has Source Text keyframes; they were removed on the copies");
                    for (var k = tprop.numKeys; k >= 1; k--) { tprop.removeKey(k); }
                }
                var tdoc = tprop.value;
                tdoc.text = line.text;
                tprop.setValue(tdoc);
                metrics = DATA.fontMetrics[tdoc.font] || readFontMetrics(tdoc.fontLocation, tdoc.font);
                if (!metrics) {
                    warnOnce("tmplmetrics " + tdoc.font, "No metrics for template font " + tdoc.font +
                             "; vertical alignment uses the text box");
                }
            } else {
                warnOnce("tmpl " + line.style, "No " + DATA.options.template + "_" + line.style + " or " +
                         DATA.options.template + " text layer in the comp; style " + line.style + " uses ASS styling");
            }
        }
        if (!layer) {
            layer = comp.layers.addText(line.text);
            font = resolveFont(line.style, st);
            metrics = font ? font.metrics : null;
            var prop = textDocProp(layer);
            var td = prop.value;
            styleTextDocument(td, line, st, font, sy);
            prop.setValue(td);
        }
        layer.name = line.name;
        layer.comment = line.comment;
        layer.startTime = 0;
        var inP = line.inPoint, outP = line.outPoint;
        if (fpsMatches(comp)) {
            // AE keeps its own frame grid (a 23.976 comp is exactly 23.976 fps): use its frame times
            inP = line.inFrame * comp.frameDuration;
            outP = line.outFrame * comp.frameDuration;
        }
        // On text layers, setting inPoint keeps the layer's length (the out point moves
        // with it), so set the in point first and trim the out point afterwards.
        layer.inPoint = inP;
        layer.outPoint = outP;
        return { layer: layer, metrics: metrics };
    }

    // Anchor the text box at the ASS alignment point: horizontally from the
    // text's bounding box, vertically from the baselines plus font ascent/descent
    // (libass's line box) when metrics are known, otherwise from the bounding box.
    function placeLayer(layer, line, metrics, sx, sy) {
        var t = line.inPoint;
        var rect = layer.sourceRectAtTime(t, false);
        var td = textDocProp(layer).valueAtTime(t, false);
        var col = line.alignment % 3;
        var ax = col === 1 ? rect.left : (col === 0 ? rect.left + rect.width : rect.left + rect.width / 2);
        var ay;
        var base = baselines(td);
        if (metrics && base) {
            var vscale = 1;
            try { if (td.verticalScale) { vscale = td.verticalScale; } } catch (e) {}
            var asc = td.fontSize * metrics.asc * vscale;
            var desc = td.fontSize * metrics.desc * vscale;
            if (line.alignment <= 3) {
                ay = base.last + desc;
            } else if (line.alignment >= 7) {
                ay = base.first - asc;
            } else {
                ay = (base.first - asc + base.last + desc) / 2;
            }
        } else {
            ay = line.alignment <= 3 ? rect.top + rect.height : (line.alignment >= 7 ? rect.top : rect.top + rect.height / 2);
        }
        var tr = layer.property(MN.transform);
        setStatic(tr.property(MN.anchor), [ax, ay]);
        setStatic(tr.property(MN.position), [line.x * sx, line.y * sy]);
        if (line.angle) { setStatic(tr.property(MN.rotation), -line.angle); }
    }

    // Template copies may carry keyframes, where setValue would throw.
    function setStatic(prop, value) {
        if (prop.numKeys > 0) {
            warnOnce("keys " + prop.matchName, "Removed " + prop.name + " keyframes copied from the template");
            for (var k = prop.numKeys; k >= 1; k--) { prop.removeKey(k); }
        }
        prop.setValue(value);
    }

    // First and last baseline y in layer space.
    function baselines(td) {
        var locs = null;
        try { locs = td.baselineLocs; } catch (e) { locs = null; }
        if (locs && locs.length >= 4) {
            return { first: locs[1], last: locs[locs.length - 1] };
        }
        return null;
    }

    function addMarkers(layer, markers) {
        var mk = layer.property(MN.marker);
        for (var i = 0; i < markers.length; i++) {
            var m = markers[i];
            var mv = new MarkerValue(m.c);
            mv.duration = m.d;
            try {
                mv.setParameters(m.p);
            } catch (e) {
                warnOnce("params", "MarkerValue.setParameters failed: " + e.toString());
            }
            mk.setValueAtTime(m.t, mv);
        }
    }

    function propByPath(layer, path) {
        var p = layer;
        for (var i = 0; i < path.length; i++) { p = p.property(path[i]); }
        return p;
    }

    // Property references go stale after addProperty, so every step re-resolves its path.
    function addAnimator(layer, color) {
        var animators = layer.property(MN.textProps).property(MN.animators);
        var anim = animators.addProperty(MN.animator);
        var index = anim.propertyIndex;
        anim.name = "ass2ae karaoke";
        var base = [MN.textProps, MN.animators, index];
        propByPath(layer, base.concat([MN.animProps])).addProperty(MN.fill);
        propByPath(layer, base.concat([MN.animProps, MN.fill])).setValue(color);
        var sels = propByPath(layer, base.concat([MN.selectors]));
        for (var i = sels.numProperties; i >= 1; i--) {
            if (sels.property(i).matchName !== MN.exprSel) { sels.property(i).remove(); }
        }
        propByPath(layer, base.concat([MN.selectors])).addProperty(MN.exprSel);
        var sel = propByPath(layer, base.concat([MN.selectors])).property(MN.exprSel);
        sel.property(MN.basedOn).setValue(BASED_ON_CHARACTERS);
        sel.property(MN.exprAmount).expression = DATA.amountExpression;
    }

    // ------------------------------------------------------------ self check ---

    function selfCheck(layer, line) {
        var mk = layer.property(MN.marker);
        if (mk.numKeys !== line.markers.length) {
            warn(line.name + ": expected " + line.markers.length + " markers, found " + mk.numKeys);
        }
        var joined = "", prev = -1e9;
        for (var k = 1; k <= mk.numKeys; k++) {
            joined += mk.keyValue(k).comment;
            var t = mk.keyTime(k);
            if (!(t > prev)) { warn(line.name + ": marker times are not strictly increasing at #" + k); }
            prev = t;
        }
        var text = textDocProp(layer).value.text;
        var expected = DATA.options.newlineCounts ? unifyNewlines(text) : stripNewlines(text);
        if (DATA.options.newlineCounts) { joined = unifyNewlines(joined); }
        if (joined !== expected) {
            warn(line.name + ": marker comments do not add up to the layer text");
        }
        return mk.numKeys;
    }

    // ------------------------------------------------------------------ main ---

    function run() {
        var comp = targetComp();
        var removed = removeGenerated(comp);
        var sx = comp.width / DATA.playRes[0];
        var sy = comp.height / DATA.playRes[1];
        var made = [];
        for (var i = 0; i < DATA.lines.length; i++) {
            var line = DATA.lines[i];
            var res = createLayer(comp, line, sy);
            // keep the block in order (KARA_0001 on top) wherever the first layer landed:
            // the comp top for new text layers, just above the template for copies
            if (made.length) { res.layer.moveAfter(made[made.length - 1].layer); }
            placeLayer(res.layer, line, res.metrics, sx, sy);
            if (line.markers.length) {
                addMarkers(res.layer, line.markers);
                if (DATA.options.withAnimator) {
                    addAnimator(res.layer, DATA.options.sungColor || DATA.styles[line.style].sung);
                }
            }
            made.push({ layer: res.layer, line: line });
        }
        var markerCount = 0;
        for (var j = 0; j < made.length; j++) {
            if (made[j].line.markers.length) { markerCount += selfCheck(made[j].layer, made[j].line); }
        }
        return { comp: comp.name, compId: comp.id, layers: made.length, markers: markerCount, removed: removed };
    }

    var summary = null;
    app.beginUndoGroup("ass2ae: " + DATA.source);
    try {
        summary = run();
    } catch (err) {
        warn("Stopped by an error: " + err.toString() + (err.line ? " (jsx line " + err.line + ")" : ""));
    } finally {
        app.endUndoGroup();
    }

    var all = DATA.warnings.concat(warnings);
    if ($.global.ASS2AE_HEADLESS) {
        $.global.ASS2AE_RESULT = { summary: summary, warnings: all, aeWarnings: warnings };
        return;
    }
    var msg = "ass2ae: " + DATA.source + "\n";
    if (summary) {
        msg += "Comp: " + summary.comp + "\nLayers: " + summary.layers + "   Markers: " + summary.markers +
               "   Replaced: " + summary.removed + "\n";
    }
    msg += "Warnings: " + all.length;
    var shown = Math.min(all.length, 15);
    for (var w = 0; w < shown; w++) { msg += "\n- " + all[w]; }
    if (all.length > shown) { msg += "\n(" + (all.length - shown) + " more; see the converter output)"; }
    alert(msg);
})();
